version: '3.1'
services:
  db:
    image: postgres:13
    container_name: "postgres_db"
    ports:
      - "5432:5432"
    networks:
      - news_network
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  my_app:
    build: .
    container_name: "SB_News"
    restart: always
    ports:
      - "8080:8080"
    networks:
      - news_network
    environment:
#      - cron-template=*/1 * * ? * *
      - spring.datasource.url=jdbc:postgresql://postgres_db:5432/postgres
    volumes:
      - "./info_by_source:/info_by_source"
networks:
  news_network:








