drop table if exists news cascade;
drop table if exists source cascade;
create table news
(
    id          int4 generated by default as identity,
    title       varchar(255) not null,
    title_topic varchar(255),
    source_id   int4         not null,
    primary key (id)
);
create table source
(
    id   int4 generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);
alter table if exists news add constraint news_fc foreign key (source_id) references source on delete cascade